config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]
  get 'welcome/index'

  resources :questions do
    resources :answers, :only => [:create, :destroy, :index]
  end

  resources :users, :only => [:show, :index] do
  member do
    get :follow
    get :unfollow
  end
end

  match 'galleries/show', to: 'galleries#show', via: 'get'

  match 'app/', to: 'app#index', via: 'get'
  match 'app/*all', to: 'app#index', via: 'get'

  resources :profiles, :only => [:show, :create, :index]

  match '/api/app/senduser', to: 'app#user', via: 'get'
  match '/api/app/sendfollows', to: 'app#follows', via: 'get'
  match '/api/app/sendquestions', to: 'app#questions', via: 'get'
  match '/api/app/sendanswers', to: 'app#answers', via: 'get'

  match '/api/app/listofusers', to: 'app#listofusers', via: 'get'
  match '/api/app/followunfollow', to: 'app#followunfollow', via: 'get'

  match '/api/app/users/follow', to: 'users#follow', via: 'get'

  match '/api/questions/edit/:id', to: 'questions#edit', via: 'get'

  match '/api/questions/:id', to: 'questions#update', via: 'post'

  match '/questions/:id/answers', to: 'answers#create', via: 'post'

  match '/notify/send', to: 'notifications#notify', via: 'get'

  match '/notify/remove', to: 'notifications#remove', via: 'delete'



  scope '/api' do
    scope '/questions' do
      get '/' => 'questions#index'
      post '/' => 'questions#create'
      delete '/' => 'questions#destroy'
      patch '/' => 'questions#update'
      scope '/senduser' do
        get '/'  => 'questions#senduser'
      end
    end
  end



  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
#Model for handling question related operations and validations
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  validates :title, :contents, presence: true,
                  length: { minimum: 5 }
  #validates :askedby, presence: true

  def self.search(search)
   where("title LIKE ?", "%#{search}%")
   #where("contents LIKE ?", "%#{search}%")
  end

  def self.anscounthash(current_user)
  	Question.where(askedby: current_user.email).collect do |f|
  	# question.each do |f|
    	count = f.answers.find_all().count()
    	ques_ans_hash = {id: f.id, title: f.title, ans_count: count}
    	ques_ans_hash
  	end
  end

end

app/controllers/questions_controller.rb
# Handles all the operations that deal with creation,
# view and deletion of the questions
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  layout 'application'
  @a = 0
  def new
    @question = Question.new
  end
  def senduser
    respond_to do |format|
    format.html # index.html.erb
    format.json { render :json => [current_user.email] }
    end
  end
  def edit
    @question = Question.find(params[:id])
    if @question.askedby != current_user.email
      flash[:info] = "You cannot edit the question asked by other user!"
      redirect_back(fallback_location: root_path)
    else
      respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => [@question] }
      end

    end
  end
  def index
    @questions = Question.all
    @posts = Question.all
    if params[:search]
      @posts = Question.search(params[:search]).order("created_at DESC")
    else
      @posts = nil
    end
      respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => [@questions] }
      end
  end

  def show
    @question = Question.find(params[:id])

    respond_to do |format|
    format.html # index.html.erb
    format.json { render :json => [@question] }
    end
  end
  def create
    @question = Question.new(question_params)
    if @question.save
    respond_to do |format|
    format.html # index.html.erb
    format.json { render :json => [@question] }
    end
  else
    render 'new'
  end

  end
  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      #redirect_to @question
        respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => [@question] }
        end

    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.askedby != current_user.email
      flash[:notice] = "You cannot delete the question asked by other user!"
      redirect_back(fallback_location: root_path)
      respond_to do |format|
        format.json {render :json => {:msg => "item deleted!"},:status => 200}
      end
    else
      @question.destroy
  end
  end
  def question_params
    params.require(:question).permit(:title, :contents, :askedby)
  end
end

app/views/questions/_form.html.erb
<%= form_for question do |f| %>

  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form-control" %>
  </p>
 <br>
  <p>
    <%= f.label :contents, "Description" %><br>
    <%= f.text_area :contents, :class => "form-control" %>
  </p>
    <%= f.hidden_field :askedby, :value => current_user.email %>
    <br>
  <p>
    <%= f.submit "Submit Question", :class => "btn btn-success" %>
  </p>

<% end %>

app/views/questions/edit.html.erb
<h1 class="h1">Edit Question</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<br>
<%= form_tag(questions_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Questions (By Title)", :class => "form-control" %>
<br>
<%= submit_tag "Search", :class => "btn btn-success" %>
<% end %>
<% if @posts.present? %>
<div class="search-results">
<h1 class="h2">Search Results</h1>
<table class="table table-bordered table-hover">
<tr>
<th>Question Title</th>
<th>Asked By</th>
<th>View Question</th>
</tr>
  <% @posts.each do |q| %>
  <tr>
  <td>
  <%= q.title %>
  </td>
  <td>
  <%= q.askedby %>
  </td>
  <td><button class="btn btn-success"><%= link_to 'View', question_path(q) %></button></td>
  </tr>
  <% end %>
  </table>
  </div>
<% else %>
  <% if @post == 1 %>
  <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
  <% end %>
<% end %>
<br>
 <div class="h1" id="heading"></div>


<ul id="nav">
<li>
<a data-url = "/profile" href="/profiles/#profile">Home</a><br>
 </li>
 </ul>
 <div id="cont">
 <script id="questionTemplate" type="text/template">

        </script>
</div>

<table id="#temp">
</table>

app/views/questions/new.html.erb
<br><br>
<h1 class="h1">Post New Question</h1>
<br>
<%= render 'form' %>

<div id="posts"></div>

app/views/questions/search.html.erb
<%= form_tag(questions_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
<%= submit_tag "Search" %>
<% end %>

<% if @posts.present? %>
  <% @posts.each do |q| %>
  <%= q.title %>
  <% end %>
<% else %>
  <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/questions/show.html.erb
<style sheet="text/css">
#editbtn a:link, #editbtn a:hover
{
	text-decoration-color: white;
	text-decoration: none;
	text-decoration-color: none;
}
</style>

<p>
  <h2 class="h2">Question: <%= @question.title %></h2>
  <h6 class="h4">Asked By: <%= @question.askedby %></h6>
</p>
<br>
<div class="desc" style="background-color: lightblue; height:150px; border-radius:25px; padding: 25px;">
<p class="p">
  <strong>Description:</strong>
  <%= @question.contents %>
</p>

<br>
</div>
<br>
<div id = "editbtn">
<a class="btn btn-warning" id="edit_question" href=<%= edit_question_path(@question) %> rel="nofollow">Edit This Question</a>

<a class="btn btn-danger" id="delete_question" data-confirm="Are you sure?" data-method="delete" href=<%= question_path(@question) %> rel="nofollow">Delete</a>

  </div>

<h2 class="h2">Add an Answer to this Question:</h2>

<%= render 'answers/form' %>

<h2 class="h2">Previous answers to this Question</h2>


<%= render @question.answers %>

<div class="clearfix"> </div>