config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]
  get 'welcome/index'

  resources :questions do
    resources :answers, :only => [:create, :destroy, :index]
  end

  resources :users, :only => [:show, :index] do
  member do
    get :follow
    get :unfollow
  end
end

  match 'galleries/show', to: 'galleries#show', via: 'get'

  match 'app/', to: 'app#index', via: 'get'
  match 'app/*all', to: 'app#index', via: 'get'

  resources :profiles, :only => [:show, :create, :index]

  match '/api/app/senduser', to: 'app#user', via: 'get'
  match '/api/app/sendfollows', to: 'app#follows', via: 'get'
  match '/api/app/sendquestions', to: 'app#questions', via: 'get'
  match '/api/app/sendanswers', to: 'app#answers', via: 'get'

  match '/api/app/listofusers', to: 'app#listofusers', via: 'get'
  match '/api/app/followunfollow', to: 'app#followunfollow', via: 'get'

  match '/api/app/users/follow', to: 'users#follow', via: 'get'

  match '/api/questions/edit/:id', to: 'questions#edit', via: 'get'

  match '/api/questions/:id', to: 'questions#update', via: 'post'

  match '/questions/:id/answers', to: 'answers#create', via: 'post'

  match '/notify/send', to: 'notifications#notify', via: 'get'

  match '/notify/remove', to: 'notifications#remove', via: 'delete'



  scope '/api' do
    scope '/questions' do
      get '/' => 'questions#index'
      post '/' => 'questions#create'
      delete '/' => 'questions#destroy'
      patch '/' => 'questions#update'
      scope '/senduser' do
        get '/'  => 'questions#senduser'
      end
    end
  end



  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/controllers/profiles_controller.rb
#Controller to maintain the User profiles in the application
class ProfilesController < ApplicationController

  def index
    @question = Question.where(askedby: current_user.email)
    @folls = current_user.followers #Followers
    @follg = current_user.all_following #Following
    @answer = Answer.where(answeredby: current_user.email)
    respond_to do |format|
      format.html # index.html.erb
      format.json {render :json => [@follg.count, @folls.count, @answer.count]}
    end
  end

  def create
    @profile = Profile.new(profile_params)
    if @question.save
      redirect_to @profile
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @question1 = Question.where(askedby: @user.email)
    @followers1 = @user.followers
    @following1 = current_user.all_following
    @answer1 = Answer.where(answeredby: @user.email)
  end

  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name)
    end
  end

app/views/profiles/index.html.erb
<!-- <br>
<h1 class="h1">My Profile</h1>
<br>
<center>

<div class="col-md-4 content-right" style="float: left;">
					<div class="cntnt-img">
					</div>
					<div class="bnr-img">
						<img src="../assets/profile-img.png" width=165px height=165px alt=""/>
					</div>
					<div class="bnr-text">
						<h1>Quick Stats</h1>

					</div>
					<div class="btm-num">
						<ul>
							<li>
								<h4><%= current_user.all_following.count %></h4>
								<h5>Following</h5>
							</li>
							<li>
								<h4><%= current_user.followers_count %></h4>
								<h5>Followers</h5>
							</li>
							<li>
								<h4><%= @answer.count %></h4>
								<h5>Answers</h5>
							</li>
						</ul>
					</div>
				</div>
				</center>

<div class="col-md-4" style="position:relative; float:left; background-color: lightgreen; padding-top:10px; width: 450px;height: 385px;">
<div class="bnr-num">
	<center><img src="../assets/details-img.png" width=160px height=160px alt=""/>
	<br><br>
	Details</center>
</div>
<table class="table">
<tr>
<td>
My Registered Email:
</td>
<td>
<%= current_user.email %>
</td>
</tr>
<tr>
<td>
No of Questions asked:
</td>
<td>
<%= @question.count %>
</td>
</tr>
<tr>
<td>
No of Questions Answered:
</td>
<td>
<%= @answer.count %>
</td>
</tr>
<br>
</table>
</div>
<div class="col-md-2" style="position:relative; border:thin; overflow:auto; float:left; background-color: #b3f2fd; padding-top:10px; width: 310px;height: 200px;">
Followers:
<br><br>
<% @followers.each #do |f| %>
<%= link_to f.email, profile_path(f) %>
<br>
<% #end %>
</div>
<br><br><br><br><br><br>
<div class="col-md-2" style="position:relative; border:thin yellow; overflow:auto; float:left; background-color: #b3f2fd; padding-top:10px; width: 310px; height: 185px;">
Following:
<br><br>
<% @following.each #do |f| %>
<%= link_to f.email, profile_path(f) %>
<br>
<% #end %>
</div>

<div class="clearfix"> </div>

<br><br>
<h3 class="h3">My Questions</h3>
<br>
<% @question.each #do |q| %>
Title: <%= link_to q.title, question_path(q) %>
<br>
<% #end %>
<br><br>
<h3 class="h3">My Answers</h3>
<br>
<% @answer.each #do |a| %>
<% @ques #= Question.find(a.question_id) %>
Answered To: <%= link_to @ques.title, question_path(@ques) %>
<br>
<% #end %>
<br><br> -->

app/views/profiles/sendfollowingcount.html.erb
Hi

app/views/profiles/show.html.erb
<!-- <br>
<h1 class="h1">User Profile: <%= @user.email %></h1>
<br>
<center>

<div class="col-md-4 content-right" style="float: left;">
					<div class="cntnt-img">
					</div>
					<div class="bnr-img">
						<img src="../assets/profile-img.png" width=165px height=165px alt=""/>
					</div>
					<div class="bnr-text">
						<h1>Quick Stats</h1>

					</div>
					<div class="btm-num">
						<ul>
							<li>
								<h4><%= @user.all_following.count %></h4>
								<h5>Following</h5>
							</li>
							<li>
								<h4><%= @user.followers_count %></h4>
								<h5>Followers</h5>
							</li>
							<li>
								<h4><%= @answer1.count %></h4>
								<h5>Answers</h5>
							</li>
						</ul>
					</div>
				</div>
				</center>

<div class="col-md-4" style="position:relative; float:left; background-color: lightgreen; padding-top:10px; width: 450px;height: 385px;">
<div class="bnr-num">
	<center><img src="../assets/details-img.png" width=160px height=160px alt=""/>
	<br><br>
	Details</center>
</div>
<table class="table">
<tr>
<td>
Registered Email:
</td>
<td>
<%= @user.email %>
</td>
</tr>
<tr>
<td>
No of Questions asked:
</td>
<td>
<%= @question1.count %>
</td>
</tr>
<tr>
<td>
No of Questions Answered:
</td>
<td>
<%= @answer1.count %>
</td>
</tr>
<br>
</table>
</div>
<div class="col-md-2" style="position:relative; float:left; background-color: #b3f2fd; padding-top:10px; width: 310px;height: 200px;">
Followers:
<br><br>
<% @followers1.each #do |f| %>
<%= link_to f.email, profile_path(f) %>
<br>
<% #end %>
<br><br><br><br><br><br>
</div>
<div class="col-md-2" style="position:relative; border:thin yellow; overflow:auto; float:left; background-color: #b3f2fd; padding-top:10px; width: 310px; height: 185px;">
Following:
<br><br>
<% @following1.each #do |f| %>
<%= link_to f.email, profile_path(f) %>
<br>
<% #end %>
</div>
<div class="clearfix"> </div>
<br><br>
<h3 class="h3">My Questions</h3>
<br>
<% @question1.each #do |q| %>
Title: <%= link_to q.title, question_path(q) %>
<br>
<% #end %>
<br><br>
<h3 class="h3">My Answers</h3>
<br>
<% @answer1.each # do |a| %>
<% @ques # = Question.find(a.question_id) %>
Answered To: <%= link_to @ques.title, question_path(@ques) %>
<br>
<% #end %>
<br><br> -->